apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

patchesStrategicMerge:
  - patch.yaml

images:
  - name: team4-memo-app
    newName: docker.io/YOUR_DOCKERHUB_USERNAME/team4-memo-app
    newTag: dev-latest

namePrefix: dev-
